from .system_prompts import (
    get_full_system_prompt,
    STEP_PROMPTS,
    COACH_IDENTITY,
    TRAINING_PHILOSOPHY,
    PERIODIZATION_FRAMEWORK,
    FMS_INTERPRETATION_GUIDE,
    EXERCISE_SELECTION_CRITERIA,
    VOLUME_AND_INTENSITY_GUIDELINES,
)

__all__ = [
    "get_full_system_prompt",
    "STEP_PROMPTS",
    "COACH_IDENTITY",
    "TRAINING_PHILOSOPHY",
    "PERIODIZATION_FRAMEWORK",
    "FMS_INTERPRETATION_GUIDE",
    "EXERCISE_SELECTION_CRITERIA",
    "VOLUME_AND_INTENSITY_GUIDELINES",
]
