import anthropic
from config import get_settings
import json


class AIService:
    """AI service using Claude for tag generation and workout planning."""

    def __init__(self):
        settings = get_settings()
        self.client = anthropic.Anthropic(api_key=settings.anthropic_api_key)
        self.model = "claude-sonnet-4-20250514"

    async def generate_exercise_tags(
        self, name: str, description: str, category: str, equipment: list[str]
    ) -> list[str]:
        """Generate AI tags for an exercise based on its details."""

        prompt = f"""Analyze this exercise and generate relevant tags for categorization and searchability.

Exercise Name: {name}
Description: {description}
Category: {category}
Equipment: {', '.join(equipment) if equipment else 'None/Bodyweight'}

Generate 5-10 relevant tags that describe:
- Target muscle groups (e.g., quadriceps, glutes, chest)
- Movement patterns (e.g., push, pull, hinge, squat)
- Training adaptations (e.g., hypertrophy, power, endurance)
- Difficulty level (e.g., beginner-friendly, advanced)
- Any special characteristics (e.g., unilateral, compound, isolation)

Return ONLY a JSON array of lowercase tags, no explanation.
Example: ["quadriceps", "compound", "lower-body", "strength", "intermediate"]"""

        try:
            message = self.client.messages.create(
                model=self.model,
                max_tokens=200,
                messages=[{"role": "user", "content": prompt}],
            )

            response_text = message.content[0].text.strip()
            # Parse JSON array from response
            tags = json.loads(response_text)
            return [tag.lower().strip() for tag in tags if isinstance(tag, str)]
        except Exception as e:
            print(f"Error generating tags: {e}")
            return []

    async def generate_workout_plan_stub(
        self,
        assessment: dict,
        coach_preferences: dict,
        training_philosophy: str,
        exercises: list[dict],
    ) -> dict:
        """
        Stub for agentic workout plan generation.

        In a full implementation, this would use the Anthropic Agent SDK
        to create a multi-step workflow:
        1. Analyze client assessment
        2. Match exercises to goals
        3. Design periodization
        4. Create daily workouts
        5. Balance volume and intensity

        For now, returns a simple template structure.
        """

        # This is a stub - in production, use Anthropic Agent SDK
        # for a proper agentic workflow

        weeks = coach_preferences.get("plan_duration_weeks", 4)
        days_per_week = assessment.get("availability", {}).get("days_per_week", 3)

        plan_structure = {
            "name": f"{weeks}-Week Training Plan",
            "weeks": weeks,
            "days_per_week": days_per_week,
            "workout_days": [],
            "notes": "Plan generated by AI - review and customize as needed.",
        }

        # Generate basic workout structure
        focus_rotation = ["Upper Body", "Lower Body", "Full Body", "Cardio/Conditioning"]

        for week in range(1, weeks + 1):
            for day in range(days_per_week):
                focus = focus_rotation[day % len(focus_rotation)]
                workout_day = {
                    "week_number": week,
                    "day_of_week": day + 1,  # 1-indexed for Mon-Sun
                    "name": f"Week {week} - Day {day + 1}",
                    "focus": focus,
                    "exercises": [],
                    "notes": f"Focus: {focus}. Adjust intensity based on recovery.",
                }

                # Add placeholder exercises based on focus
                if "Upper" in focus:
                    workout_day["exercises"] = [
                        {
                            "exercise_name": "Bench Press",
                            "sets": 4,
                            "reps": "8-10",
                            "rest_seconds": 90,
                        },
                        {
                            "exercise_name": "Barbell Row",
                            "sets": 4,
                            "reps": "8-10",
                            "rest_seconds": 90,
                        },
                        {
                            "exercise_name": "Overhead Press",
                            "sets": 3,
                            "reps": "10-12",
                            "rest_seconds": 60,
                        },
                    ]
                elif "Lower" in focus:
                    workout_day["exercises"] = [
                        {
                            "exercise_name": "Squat",
                            "sets": 4,
                            "reps": "6-8",
                            "rest_seconds": 120,
                        },
                        {
                            "exercise_name": "Romanian Deadlift",
                            "sets": 3,
                            "reps": "8-10",
                            "rest_seconds": 90,
                        },
                        {
                            "exercise_name": "Leg Press",
                            "sets": 3,
                            "reps": "10-12",
                            "rest_seconds": 60,
                        },
                    ]
                elif "Cardio" in focus:
                    workout_day["exercises"] = [
                        {
                            "exercise_name": "Running",
                            "duration_minutes": 30,
                            "target_hr": 140,
                            "notes": "Zone 2 cardio",
                        },
                    ]
                else:
                    workout_day["exercises"] = [
                        {
                            "exercise_name": "Deadlift",
                            "sets": 4,
                            "reps": "5",
                            "rest_seconds": 180,
                        },
                        {
                            "exercise_name": "Pull-ups",
                            "sets": 3,
                            "reps": "max",
                            "rest_seconds": 90,
                        },
                        {
                            "exercise_name": "Plank",
                            "sets": 3,
                            "reps": "60 sec",
                            "rest_seconds": 60,
                        },
                    ]

                plan_structure["workout_days"].append(workout_day)

        return plan_structure
